In [ ]:
from sklearn.preprocessing import MinMaxScaler, StandardScaler,Normalizer

In [2]:
data = [[234.45, 0],[2,0.567],[2.1,1],[2.67,1]]

In [3]:
data

[[234.45, 0], [2, 0.567], [2.1, 1], [2.67, 1]]

In [6]:
import numpy as np

In [7]:
data = np.array(data)

In [8]:
data

array([[234.45 ,   0.   ],
       [  2.   ,   0.567],
       [  2.1  ,   1.   ],
       [  2.67 ,   1.   ]])

In [9]:
scaler_minmax =  MinMaxScaler()
scaler_minmax

,feature_range,"(0, ...)"
,copy,True
,clip,False


In [10]:
data_minmax = scaler_minmax.fit_transform(data)

In [11]:
data_minmax

array([[1.00000000e+00, 0.00000000e+00],
       [0.00000000e+00, 5.67000000e-01],
       [4.30200043e-04, 1.00000000e+00],
       [2.88234029e-03, 1.00000000e+00]])

In [13]:
scaler_stand = StandardScaler()
scaler_stand

,copy,True
,with_mean,True
,with_std,True


In [15]:
data_stand = scaler_stand.fit_transform(data)
data_stand

array([[ 1.73204521, -1.56324956],
       [-0.57990121, -0.18208477],
       [-0.57890661,  0.87266717],
       [-0.57323739,  0.87266717]])

In [16]:
data_norm = Normalizer().fit_transform(data)
data_stand

array([[ 1.73204521, -1.56324956],
       [-0.57990121, -0.18208477],
       [-0.57890661,  0.87266717],
       [-0.57323739,  0.87266717]])

In [17]:
import pandas as pd


In [27]:
df = pd.read_csv("/Users/rashmithav/Documents/Dataminds/04. Datasets-Masters/Dataset-Master 1/VC_Startups.csv")
df= pd.get_dummies(df)


In [19]:
df.head()

,R&D Spend,Administration,Marketing Spend,State,Profit
0,165349.20,136897.80,471784.10,NaN,192261.83
1,162597.70,151377.59,443898.53,NaN,191792.06
2,153441.51,101145.55,407934.54,Florida,191050.39
3,144372.41,118671.85,383199.62,New York,182901.99
4,142107.34,91391.77,366168.42,Florida,166187.94


In [28]:
x = df.iloc[: ,:-1]
y = df.iloc[: ,-1]

In [29]:
from sklearn.preprocessing import StandardScaler

In [30]:
sr = StandardScaler()
sr

,copy,True
,with_mean,True
,with_std,True


In [33]:
x_scaling = sr.fit_transform(x)
x_scaling

array([[ 1.99139612,  0.53816648,  2.08481328,  2.01120333, -0.68599434,
        -0.68599434],
       [ 1.93122482,  1.06424848,  1.85907913,  1.99942997, -0.68599434,
        -0.68599434],
       [ 1.73099227, -0.76078986,  1.56795003,  1.98084225, -0.68599434,
         1.45773797],
       [ 1.53266425, -0.12402159,  1.36772044,  1.77662724, -0.68599434,
        -0.68599434],
       [ 1.48313047, -1.11516573,  1.2298526 ,  1.35774012, -0.68599434,
         1.45773797],
       [ 1.25940563, -0.80914215,  1.20308189,  1.12724963, -0.68599434,
        -0.68599434],
       [ 1.31929395,  0.91242657, -0.70041707,  1.10548055,  1.45773797,
        -0.68599434],
       [ 1.22488023,  0.8517951 ,  0.88750026,  1.09620987, -0.68599434,
         1.45773797],
       [ 1.01153923,  0.96765435,  0.78822791,  1.00746967, -0.68599434,
        -0.68599434],
       [ 1.07260408, -0.4870772 ,  0.73454443,  0.94602247,  1.45773797,
        -0.68599434],
       [ 0.60414049, -0.4175033 ,  0.12077485,  0.